backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/img/uploads" # where files are stored in the REPO
# public_folder: "/img/uploads"    # COMMENTED defaults as the one above

collections:
  - name: "artigo"  # Used in routes, e.g., /admin/collections/blog
    label: "Artigos" # Used in the UI
    folder: "content/artigos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title",    name: "title",    widget: "string" }
      - { label: "Type",     name: "type",     widget: "hidden", default: "article" }
      - { label: "Date",     name: "date",     widget: "datetime" }
      - { label: "Author",   name: "author",   widget: "string" }
      - { label: "Abstract", name: "abstract", widget: "text" }
      - { label: "Image",    name: "image",    widget: "image" }
      - { label: "Body",     name: "body",     widget: "markdown" }
    # filter: # allows to filter posts that are visible to the editor to change
    #   field: language
    #   value: en
  - name: "gwn"
    label: "GWN"
    folder: "content/gwn"
    create: true
    slug: "gwn/{{year}}/{{month}}/{{day}}/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "hidden", default: "news" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Climate Policy", "Extreme Weather", "Renewable Energy", "Wildlife & Ecosystems", "Environmental Justice", "Scientific Research", "Carbon Emissions", "Deforestation", "Sustainability", "Oceans & Water", "Agriculture & Food", "Climate Activism"], default: "Climate Policy" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Abstract", name: "abstract", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }